Feature/tmux apply improvements
jubnzv/go-tmux pull request #19
Opened 2024-08-03 04:13 UTC by yorick1989

I was using [create-session.go](https://github.com/jubnzv/go-tmux/blob/master/examples/create-session/create-session.go) for testing this Go package but I found out that the `server.Sessions` slice and `session` struct were missing session, window and pane id/name information after initiating / applying the configuration.

I made the following changes to solve this problem:
- I updated the Apply method in the [configuration.go](https://github.com/yorick1989/go-tmux/blob/aa164d717860f9f57ce2c97c1fce212956d00855/configuration.go#L38) file:
  -  It uses the `NewSession`, `NewWindow` and `SplitPane` methods for initiating the session, windows and panes.
  - Assigns the Ids and Names properly.
- The `NewSession` and `NewWindow` methods now support additional arguments to be added to the default tmux command-line agruments.
- The new `SplitPane` method was added to [window.go](https://github.com/yorick1989/go-tmux/blob/aa164d717860f9f57ce2c97c1fce212956d00855/window.go#L78C1-L100C2) for creating new panes inside of a window.
- The `ListPanes` method in [window.go](https://github.com/yorick1989/go-tmux/blob/aa164d717860f9f57ce2c97c1fce212956d00855/window.go#L45C1-L47C2) now requires the `SessionName` for pulling the panes. This because it didn't work properly if there were multiple sessions created.

Hopefully you find these changes valid too and will this PR be merged into your repository.

Let me know if my code need any improvements.

Thanks!

Yorick

2024-08-03 11:59 UTC, yorick1989 commented
I've also adjusted the following in [pane.go](https://github.com/yorick1989/go-tmux/blob/feature/tmux_apply_improvements/pane.go):
- Added the Pipe method.
- Renamed (the struct Pipe) ID to Id for consistency.
- Added the pane Index to the Pipe struct.
- Use SessionName, WindowName and Pane Index to target pane commands.

2024-08-07 01:34 UTC, jubnzv requested changes
Hey @yorick1989,

Thank you for the contribution.

I see the point; it should work as expected. I have only a few styling comments and suggest not breaking backward compatibility by renaming things.

Otherwise, LGTM.

2024-08-07 01:34 UTC, jubnzv commented on window.go
> +
```suggestion
```

2024-08-07 01:34 UTC, jubnzv commented on window.go
> +
```suggestion
```

2024-08-07 01:34 UTC, jubnzv commented on pane.go
> +			Id:          paneId,
We should not rename public entries this to don't break backward compatibility for library's users.

```suggestion
			ID:          paneId,
```

2024-08-07 01:34 UTC, jubnzv commented on configuration.go
> +
```suggestion
```

2024-08-07 01:34 UTC, jubnzv commented on configuration.go
> +
```suggestion
```

2024-08-07 01:34 UTC, jubnzv commented on configuration.go
> +
```suggestion
```

2024-08-07 01:34 UTC, jubnzv commented on configuration.go
> +
```suggestion
```

2024-08-07 01:34 UTC, jubnzv commented on configuration.go
> +
```suggestion
```

2024-08-07 01:34 UTC, jubnzv commented on pane.go
> +	Id          int
```suggestion
	ID          int
```

2024-08-07 01:34 UTC, jubnzv commented on pane.go
> +		Id:          id,
```suggestion
		ID:          id,
```

2024-08-07 10:10 UTC, yorick1989 commented
> Hey @yorick1989,
> 
> Thank you for the contribution.
> 
> I see the point; it should work as expected. I have only a few styling comments and suggest not breaking backward compatibility by renaming things.
> 
> Otherwise, LGTM.

Sounds good. Let me know if it can be merged with your repository this way =).

Thanks!

Yorick

2024-08-07 10:12 UTC, yorick1989 reviewed
All looks good! Hopefully this is good enough :).

2024-08-07 14:26 UTC, jubnzv commented
Thank you!

Could we also make `golang-ci` happy? https://github.com/jubnzv/go-tmux/actions/runs/10282424723/job/28466439660?pr=19#step:4:25

2024-08-07 17:43 UTC, yorick1989 commented
> Thank you!
> 
> Could we also make `golang-ci` happy? https://github.com/jubnzv/go-tmux/actions/runs/10282424723/job/28466439660?pr=19#step:4:25

Good finding. I fixed the int to string converter @ https://github.com/jubnzv/go-tmux/pull/19/commits/30bebe31e254369249c519a3b18c083c862fe31c . Please verify and hopefully this will pass through the linter.

2024-08-08 01:42 UTC, merged